export const path = {
  personImage: ".person-wrapper",
  developerImage: ".developer-wrapper",
  personTabs: ".person-navigation-wrapper",
  developerTabs: ".developer-navigation-wrapper",
  personDeveloperWrapper: ".person-developer-content",
  experience: ".experience-container",
  experienceTitle: ".experience-title",
  experienceBottomLine: ".bottom-line-experience",
  experienceCloseButton: ".experience-close-button",
  aboutMe: ".about-me-container",
  aboutMeTitle: ".about-me-title",
  aboutMeBottomLine: ".bottom-line-about-me",
  aboutMeCloseButton: ".about-me-close-button",
  aboutMeText: ".about-me-text",
  loadingLine: ".loading-line",
  loadingPage: ".loading-page-wrapper",
  mainContent: ".content-wrapper",
  mainVerticalLine: ".vertical-line",
  layoutHeader: ".header-text-wrapper",
  layoutFooter: "footer",
  experienceList: ".experience-item-container",
};
